name: おうちコープ注文チェック
"on":                                                                       
    schedule:
      - cron: '0 23 * * *'  # 8:00 JST
      - cron: '0 3 * * *'   # 12:00 JST
      - cron: '0 9 * * *'   # 18:00 JST
    workflow_dispatch:

